---
? ''
: - octodns:
      cloudflare:
        proxied: false
    type: ALIAS
    value: parkr.github.io.
  - type: MX
    values:
    - exchange: spool.mail.gandi.net.
      preference: 10
    - exchange: fb.mail.gandi.net.
      preference: 50
  - type: TXT
    values:
    - google-site-verification=pNnerRpbLyMgcRJQRxWsCcW0vHTt3vEmcbp7Jj5JbJo
    - keybase-site-verification=PJ3ywix5C5Hnd6Fkt0GzQGKSjbKy_YghlgAGBCf03fM
    - v=spf1 include:_mailcust.gandi.net ?all
imap:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: access.mail.gandi.net.
pop:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: access.mail.gandi.net.
smtp:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: relay.mail.gandi.net.
stash:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
webmail:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: webmail.gandi.net.
www:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: parkr.github.io.
