---
? ''
: - octodns:
      cloudflare:
        proxied: false
    type: ALIAS
    value: parkr.github.io.
  - type: TXT
    values:
      - v=spf1 -all # SPF record to block all mail
      - v=DMARC1; p=reject; adkim=s; aspf=s; # DMARC policy to block all mail
'*':
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: kondwani.parkermakes.tools.
www:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkers.photos.
