---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 3600
    enforce_order: true
zones:
  byparker.com.:
    sources:
      - config
    targets:
      - cloudflare
  keltermoore.com.:
    sources:
      - config
    targets:
      - cloudflare
  parkermakes.tools.:
    sources:
      - config
    targets:
      - cloudflare
  parkermoo.re.:
    sources:
      - config
    targets:
      - cloudflare
  parkermoore.de.:
    sources:
      - config
    targets:
      - cloudflare
  parker.codes.:
    sources:
      - config
    targets:
      - cloudflare
  parkers.link.:
    sources:
      - config
    targets:
      - cloudflare
  parkers.photos.:
    sources:
      - config
    targets:
      - cloudflare
